umap:
  n_components: 5
  n_neighbors: 15
  min_dist: 0.0
  random_state: 42

hdbscan:
  min_samples: 5
  gen_min_span_tree: True
  prediction_data: True

bertopic:
  calculate_probabilities: False
  verbose: True
  min_topic_size: 10
  min_similarity: 0.7

hardware: GPU

reddit:
  client_id: 'client_id'
  client_secret: 'client_secret'
  redirect_uri: 'http://127.0.0.1:3000/profile'
  user_agent: 'r_aus_astro by Due_recordings9516'

ausreddit:
  api_key: 'api_key'

open_ai:
  api_key: 'api_key'  